version: '3.8'

services:
#  policija:
#    container_name: policija
#    build:
#      context: ./Policija/
#      dockerfile: Dockerfile
#    restart: on-failure
#    ports:
#      - 8080:8080
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlbaza:3306/policija
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_DATASOURCE_USERNAME: root
#  #      DB_PORT: 3307
#  mysqlbaza:
#    image: mysql
#    container_name: mysqlbaza
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USERNAME: root
#      MYSQL_DATABASE: policija
#    ports:
#      - 3307:3306
#    volumes:
#      - ./baza:/mysql/data1

  gradjanin:
    build:
      context: ./Gradjanin/
      dockerfile: Dockerfile
    restart: on-failure
    container_name: gradjanin
    ports:
      - 8084:8084
    environment:
      MONGO_DB_URL: mongodb://mongodb:27017
    #    depends_on:
    #      - mongodb
    links:
      - mongodb


  mongodb:
    image: mongo
    #    restart: always
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - ./mongobaza:/mongodb/data

#  mongo-express:
#    image: mongo-express
#    restart: always
#    container_name: mongo-express
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongodb
#      #      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      #      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: admin

#  tuzilastvo:
#    container_name: tuzilastvo
#    build:
#      context: ./Tuzilastvo/
#      dockerfile: Dockerfile
#    restart: on-failure
#    ports:
#      - 8082:8082
#    environment:
#      spring.datasource.url: jdbc:postgresql://postgres_container:5432/postgres
#      spring.datasource.username: root
#      spring.datasource.password: root
#    links:
#      - postgres
#
#  sudstvo:
#    build:
#      context: ./Sudstvo/
#      dockerfile: Dockerfile
#    restart: on-failure
#    container_name: sudstvo
#    ports:
#      - 8083:8083
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlbaza2:3306/sudstvo
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_DATASOURCE_USERNAME: root
#
#  mysqlbaza2:
#    image: mysql
#    container_name: mysqlbaza2
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USERNAME: root
#      MYSQL_DATABASE: sudstvo
#    ports:
#      - 3308:3306
#    volumes:
#      - ./baza:/mysql/data
#
#
#
#
#  postgres:
#    container_name: postgres_container
#    image: postgres
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root
#      PGDATA: /data/postgres
#    volumes:
#      - ./postgresbaza:/postgres/data
#    ports:
#      - 5432:5432
##    networks:
##      - postgres
#    restart: unless-stopped
#
#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#
#    ports:
#      - 5050:80
##    networks:
##      - postgres
#    restart: unless-stopped
#



